[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["derive"] }
proc-macro2 = "1.0.66"
quote = "1.0.33"
ungrammar = "1.16.1"
xshell = "0.2.5"
