[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
convert_case = "0.6.0"
anyhow = "1.0.75"
proc-macro2 = "1.0.66"
quote = "1.0.33"
thiserror = "1.0.48"
ungrammar = "1.16.1"
xshell = "0.2.5"
