type StrSlice = &'static [&'static str];

pub struct KindData {
    pub punctuation: &'static [(&'static str, &'static str)],
    pub keywords: StrSlice,
    pub tokens: StrSlice,
    pub nodes: StrSlice,
}

pub const KIND_DATA: KindData = KindData {
    punctuation: &[
        (";", "Semicolon"),
        (",", "Comma"),
        ("(", "LeftParen"),
        (")", "RightParen"),
        ("{", "LeftCurly"),
        ("}", "RightCurly"),
        ("[", "LeftBracket"),
        ("]", "RightBracket"),
        ("<", "LeftAngle"),
        (">", "RightAngle"),
        ("@", "At"),
        ("#", "Pound"),
        ("~", "Tilde"),
        ("?", "Question"),
        ("$", "Dollar"),
        ("&", "Amp"),
        ("|", "Pipe"),
        ("+", "Plus"),
        ("*", "Star"),
        ("/", "Slash"),
        ("^", "Caret"),
        ("%", "Percent"),
        ("_", "Underscore"),
        (".", "Dot"),
        ("..", "DoubleDot"),
        ("..=", "DoubleDotEq"),
        (":", "Colon"),
        ("::", "DoubleColon"),
        ("=", "Eq"),
        ("==", "DoubleEqual"),
        ("=>", "FatArrow"),
        ("!", "Bang"),
        ("!=", "NotEq"),
        ("-", "Minus"),
        ("->", "ThinArrow"),
        ("<=", "LtEq"),
        (">=", "GtEq"),
        ("+=", "PusEq"),
        ("-=", "MinusEq"),
        ("|=", "PipeEq"),
        ("&=", "AmpEq"),
        ("^=", "CaretEq"),
        ("/=", "SlashEq"),
        ("*=", "StarEq"),
        ("%=", "PercentEq"),
        ("&&", "DoubleAmp"),
        ("||", "DoublePipe"),
        ("<<", "ShiftLeft"),
        (">>", "ShiftRight"),
        ("<<=", "ShiftLeftEq"),
        (">>=", "ShiftRightEq"),
    ],
    keywords: &[],
    tokens: &["WhiteSpace", "Comment"],
    nodes: &["SourceFile"],
};
