[package]
name = "libsakura"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
drop_bomb = "0.1.5"
rowan = "0.15.11"
unicode-xid = "0.2.4"
quote = "1.0.33"

[dev-dependencies]
expect-test = "1.4.1"
panic-control = "0.1.4"
