[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rowan = "0.15"
parser = { path = "../parser" }

[dev-dependencies]
ungrammar = "1.16"
